include: package:pedantic_mono/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gform.dart"
    - "**/firebase_options*.dart"
    - "*/.github/workflows/flutter_*.yaml"
    - "*/functions/*.js"
    - "analysis_options.yaml"
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    hack: ignore
    
custom_lint:
  enable_all_lint_rules: false
  rules:
    - unsafe_null_assertion: false
    - unstable_enum_values: false
