name: cores_core
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  logger: any
  riverpod: any
  uuid: any

dev_dependencies:
  custom_lint: any
  nilts: any
  pedantic_mono: any
  riverpod_lint: any

resolution: workspace
