name: lint
description: A new Flutter package project.
version: 0.0.1
homepage: https://yakuran.notion.site/Yakuran-f3e102528a1d468994e5db69aeac8279

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer:
  flutter:
    sdk: flutter
  custom_lint_builder: 
  custom_lint: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
