name: "Setup Android Config Files"
description: "setup-android-config-files"

runs:
  using: "composite"
  steps:
    # key.jksファイルの生成(base64で受け取る)
    - name: Create key.jks
      shell: bash
      run: echo -n $ANDROID_KEY_JKS | base64 -d > apps/app/android/app/key.jks

    # Secrets から key.properties を生成
    # key.properties には各種シークレットな文字列なり file name なりを渡している
    - name: Create key.properties
      shell: bash
      run: |
        echo 'storeFile=./key.jks' > apps/app/android/key.properties
        echo 'storePassword=$STORE_PASSWORD' >> apps/app/android/key.properties
        echo 'keyPassword=$KEY_PASSWORD' >> apps/app/android/key.properties
        echo 'keyAlias=$KEY_ALIAS' >> apps/app/android/key.properties
