name: "Setup Config Files"
description: "setup-config-files"

runs:
  using: "composite"
  steps:
    - name: ⚙️Create dart-define
      run: |
        mkdir -p apps/app/dart_defines
        echo -n $DART_DEFINE_JSON | base64 -d > apps/app/dart_defines/prod.json
      shell: bash

    - name: 🔥Create Firebase env
      run: |
        mkdir -p packages/infrastructure/firebase/scripts
        mkdir -p packages/infrastructure/firebase/scripts/env
        echo -n $ENV_FILE | base64 -d > ${ENV_PATH}/.env
        echo -n $DEV_ENV_FILE | base64 -d > ${ENV_PATH}/.env.dev
      shell: bash
      env: 
        ENV_PATH: packages/infrastructure/firebase/scripts/env

    - name: 🐱Create RevenueCat env
      run: |
        mkdir -p packages/infrastructure/revenue_cat/scripts
        mkdir -p packages/infrastructure/revenue_cat/scripts/env
        echo -n $ENV_FILE | base64 -d > ${ENV_PATH}/.env
        echo -n $DEV_ENV_FILE | base64 -d > ${ENV_PATH}/.env.dev
      shell: bash
      env: 
        ENV_PATH: packages/infrastructure/revenue_cat/scripts/env
