// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzpLm8M3upgNzjTUB1-w3bxCD6ZiOMkUo',
    appId: '1:911045633649:web:b455db7199851ab3b61dd0',
    messagingSenderId: '911045633649',
    projectId: 'family-wish-list-ad3c7',
    authDomain: 'family-wish-list-ad3c7.firebaseapp.com',
    storageBucket: 'family-wish-list-ad3c7.appspot.com',
    measurementId: 'G-R5N5KBZ8V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm8rC322A4tECRB3WSlMaUyO6wWMPmE0E',
    appId: '1:911045633649:android:6766170ce81e45c4b61dd0',
    messagingSenderId: '911045633649',
    projectId: 'family-wish-list-ad3c7',
    storageBucket: 'family-wish-list-ad3c7.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJc99a39iAKaOt39zQAmyCaTDSDz9NRmQ',
    appId: '1:911045633649:ios:648543df6dcff91bb61dd0',
    messagingSenderId: '911045633649',
    projectId: 'family-wish-list-ad3c7',
    storageBucket: 'family-wish-list-ad3c7.appspot.com',
    androidClientId: '911045633649-9dv6inmmpqroc2nt9rjghre7mrpm6bsl.apps.googleusercontent.com',
    iosClientId: '911045633649-fifjfbd1ntmmfhi3bkbkeciu5uhs7m77.apps.googleusercontent.com',
    iosBundleId: 'com.yakuran.familyWishList',
  );
}
