name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:
    # https://github.com/kuhnroyal/flutter-fvm-config-action
    - name: Setup flutter
      uses: |
        actions/checkout@v4
        kuhnroyal/flutter-fvm-config-action/setup@v3

    # NOTE: 後述の melosコマンドが実行できないためPATHを通します。
    # PUB_CACHE: $HOME/.pub-cache に設定
    - name: Export PUB_CACHE
      run: |
        echo "PUB_CACHE=$HOME/.pub-cache" >> "$GITHUB_ENV"
        echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Setup melos
      run: |
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION
        melos bootstrap
      shell: bash
