name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

inputs:
  code-generation:
    description: "Code generation mode: env, all, or none"
    required: false
    default: "env"

runs:
  using: "composite"
  steps:

    # This action parses .fvmrc and installs Flutter via subosito/flutter-action.
    - name: ⚙️Setup Flutter
      uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - name: 📦Resolve dependencies
      run: flutter pub get
      shell: bash

    - name: 🔐Generate environment code
      if: inputs.code-generation == 'env'
      run: >-
        dart run build_runner build --workspace --force-jit
        --build-filter=package:infrastructure_firebase/env/env.g.dart
        --build-filter=package:infrastructure_firebase/env/env.dev.g.dart
        --build-filter=package:infrastructure_revenue_cat/env/env.g.dart
      shell: bash

    - name: ♻️Regenerate all code
      if: inputs.code-generation == 'all'
      run: dart run build_runner build --workspace --force-jit
      shell: bash
