name: "Setup Code"
description: "Setup Code"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create dart-define
      run: |
        mkdir -p apps/app/dart_defines
        echo -n ${{ secrets.DART_DEFINE_JSON }} | base64 -d > apps/app/dart_defines/prod.json
      shell: bash

    - name: Create Firebase Conf
      run: |
        echo -n ${{ secrets.FIREBASE_OPTIONS }} | base64 -d > apps/app/lib/firebase_options.dart
        echo -n ${{ secrets.FIREBASE_OPTIONS_DEV }} | base64 -d > apps/app/lib/firebase_options_dev.dart
        mkdir -p apps/app/android/app/src/prod/
        echo -n ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > apps/app/android/app/src/prod/google-services.json
        mkdir -p apps/app/ios/prod/
        echo -n ${{ secrets.GOOGLE_INFO_PLIST }} | base64 -d > apps/app/ios/prod/GoogleService-Info.plist
      shell: bash

    - name: Create env
      run: |
        mkdir -p apps/app/scripts
        mkdir -p apps/app/scripts/env
        echo -n ${{ secrets.ENV_FILE }} | base64 -d > apps/app/scripts/env/.env
        echo -n ${{ secrets.DEV_ENV_FILE }} | base64 -d > apps/app/scripts/env/.env.dev
      shell: bash
