name: Flutter Build
on:
  workflow_dispatch:
    inputs:
      release_type:
        required: true
        type: choice
        description: ビルド対象のプラットフォームを指定します
        options:
          - all
          - android
          - ios

jobs:
  # Android
  flutter_build_android:
    if: ${{ github.event.inputs.release_type == 'android' || github.event.inputs.release_type == 'all'}}
    name: 🤖Build for Android
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # Android用の環境変数
    env:
      # Google Play 認証用サービスアカウント JSON キー
      GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS }}

      # Android 署名用情報
      ANDROID_KEYSTORE_FILENAME: ${{ vars.ANDROID_KEYSTORE_FILENAME }}
      ANDROID_KEY_ALIAS: ${{ vars.ANDROID_KEY_ALIAS }}
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # Google Play アプリの設定
      GOOGLE_PLAY_PACKAGE_NAME: ${{ vars.GOOGLE_PLAY_PACKAGE_NAME }}
    steps:
      # チェックアウト
      - name: 💾Checkout
        uses: actions/checkout@v4

      - name: ☕Setup Java and Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
          cache-dependency-path: |
            apps/app/android/**/*.gradle*
            apps/app/android/**/gradle-wrapper.properties

      - name: 🐍Setup Python and pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: .github/requirements-cd.txt

      - name: 🪄Install Codemagic CLI tools
        run: pip install --disable-pip-version-check -r .github/requirements-cd.txt

      # セットアップ
      - name: ⚙️Setup Config Files
        uses: ./.github/actions/setup-config-files
        env: # Set the secret as an input
          DART_DEFINE_JSON: ${{ secrets.DART_DEFINE_JSON }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
      - name: ⚙️Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime
        with:
          code-generation: env

      # Android用の設定ファイルを設定
      - name: ⚙️Setup Android keystore
        run: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > apps/app/android/app/$ANDROID_KEYSTORE_FILENAME

      - name: ⚙️Create key.properties
        run: |
          cat > apps/app/android/key.properties << EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=$ANDROID_KEYSTORE_FILENAME
          EOF

      # ビルド
      - name: 🛠️Build for Android
        run: dart run melos run build:app:android --no-select

      # ビルドしたaabをGithub Actionsにアップロード
      - name: "🚀Deploy Bundle"
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: apps/app/build/app/outputs/bundle/release/app-release.aab
          retention-days: 7

      - name: 🚀Publish to Google Play
        run: |
          google-play bundles publish \
          --bundle "apps/app/build/app/outputs/bundle/release/app-release.aab" \
          --track internal \

  # iOS
  flutter_build_ios:
    if: ${{ github.event.inputs.release_type == 'ios' || github.event.inputs.release_type == 'all'}}
    name: 🍎Build for iOS
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APP_STORE_CONNECT_KEY_IDENTIFIER }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      DIST_CERTIFICATE: ${{ secrets.CERTIFICATES_P12 }}
      DIST_CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      DIST_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      APP_STORE_APPLE_ID: ${{ vars.APP_STORE_APPLE_ID }}
      EXPORT_OPTIONS: ${{ secrets.EXPORT_OPTIONS }}
      CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
    steps:
      # チェックアウト
      - name: 💾Checkout
        uses: actions/checkout@v4

      - name: 🐍Setup Python and pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: .github/requirements-cd.txt

      - name: 🪄Install Codemagic CLI tools
        run: pip install --disable-pip-version-check -r .github/requirements-cd.txt

      # セットアップ
      - name: ⚙️Setup Config Files
        uses: ./.github/actions/setup-config-files
        env: # Set the secret as an input
          DART_DEFINE_JSON: ${{ secrets.DART_DEFINE_JSON }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
      - name: ⚙️Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime
        with:
          code-generation: env

      - name: 📦Restore CocoaPods download cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('apps/app/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: ⚙️Set up keychain
        run: keychain initialize

      - name: ⚙️Fetch signing files
        run: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
          --type IOS_APP_STORE \
          --create       

      - name: ⚙️Set up signing certificate
        run: keychain add-certificates

      - name: ⚙️Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: ⚙️Create ExportOptions
        run: |
          echo -n $EXPORT_OPTIONS | base64 -d > apps/app/ExportOptions.plist

      - name: 🛠️Build for iOS
        working-directory: apps/app
        run: |
          # Runner上で生成されたexport-optionsを指定
          flutter build ipa --no-pub --export-options-plist=$HOME/export_options.plist --dart-define-from-file=dart_defines/prod.json

      - name: 🚀Publish the app to App Store Connect
        run: |
          # ipaファイルを検索して変数に格納
          # 複数見つかった場合は head -n 1 で最初の1つだけを取得
          APP_FILE=$(find apps/app/build/ios/ipa -name "*.ipa" | head -n 1)

          echo "Found IPA file: $APP_FILE"

          if [ -z "$APP_FILE" ]; then
            echo "Error: .ipa file not found!"
            exit 1
          fi

          # パブリッシュ実行
          app-store-connect publish --path "$APP_FILE"
