name: Flutter Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  flutter_test:
    # if: ${{ false }}
    name: 🧪Test
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    timeout-minutes: 30
    steps:
      # チェックアウト
      - name: 💾Checkout
        uses: actions/checkout@v4

      - name: ⚙️Setup Config Files
        uses: ./.github/actions/setup-config-files
        env:
          DART_DEFINE_JSON: ${{ secrets.DART_DEFINE_JSON }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
          DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
      - name: ⚙️Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # 実行
      - name: 🧪Test
        run: dart run melos run test:ci --no-select
